networks:
  publish_net:
    external: true
    name: ${PUBLISH_NETWORK}

services:
  postgres_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_EMAIL:-password}
    networks:
      - default
      - publish_net
    volumes:
      - pg_data:/var/lib/pgadmin

volumes:
  pg_data:
    external: true
    name: ${VOLUME_PG_DATA:-pg_data}
